[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
description = "Adds SCP-1507 to Lethal Company as a new enemy"
websiteUrl = "https://github.com/FelixAllard/SCP1507LC"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
TheWeavers-LethalBestiary = "1.2.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./Packages"

[[build.copy]]
source = "../bin/Release/netstandard2.1/TheWeavers.SuffleShift.dll"
target = "plugins/SCP1507/"


[[build.copy]]
source = "./CHANGELOG.md"
target = "/"
[[build.copy]]
source = "./License.txt"
target = "/"

[publish]
communities = [ "lethal-company", ]
[publish.categories]
# Get the list of categories from https://thunderstore.io/api/experimental/community/lethal-company/category/
lethal-company = [ "bepinex", "clientside", "serverside", "monsters", "mods", ]