[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
description = "A mod that swap the position of each player every certain ammount of time! Modify the configs and take on the challenge!"
websiteUrl = "https://github.com/FelixAllard/ShuffleShiftLC"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
xilophor-StaticNetcodeLib = "1.0.3"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./Packages"

[[build.copy]]
source = "../bin/Release/netstandard2.1/TheWeavers.SuffleShift.dll"
target = "plugins/SCP1507/"


[[build.copy]]
source = "./CHANGELOG.md"
target = "/"
[[build.copy]]
source = "./License.txt"
target = "/"

[publish]
communities = [ "lethal-company", ]
[publish.categories]
# Get the list of categories from https://thunderstore.io/api/experimental/community/lethal-company/category/
lethal-company = [ "mods", "clientside", "serverside", "misc", "tools"]